language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
env:
  global:
  - boardname: trellist_test
  - done_list: Finished
  - releases: Releases
  - secure: khCgRPmn2q8WcTNBm7mGOpsI2YKP5HWtWqfgr7Pr4hjHZDQpUxp5m1TqaPvtMvHjQxcZU8K3IkaYnFC9hV0VNM/1A4QOEWtWdUISbaDnEEbHaIGn51YgKYwiiMq1hccZFX4iUHaj0kXaa2AGRRf39yV+n2DvzwDQt37UuDQ6Akd0IXpZKqCK/+pcQX5KCYPtYtSqg7wNIUouhfEzvmnyBgoaKOXVUlzxN8rXsJIjnhTjQw6J/zJc98JCKg9mw7rTwGUlOfOejWQh8wXqNVvguy10IdhKJWs+5YsJ1/no17J5sRNzyCWeRldi/I9FKB0anZXlO2f4xrH3ZUatf0lRl6Sgte3aoHMsCPYgl3GEK5QC3+qz/E1Qt/0bDVw0fAMzuenpTJG5zVunBV4JdBlXyf3g3OALHkiTxoGcu084erGPE3xKJwLtASGZhryc37Dht38JXOzyB7JCVip3XKc5VLPKiHjPcz7cfTiw6ZQXWz3S8jchRQodT2l70+5OosBmI0SdNwytiAxv/fCKug+4XVS4mBbS1IFPsziHyN8cb4SNX5i4n4asS09HjDTKG5ZEwLMdNgU7TOD3lJ2EwCewAvV9zQfuYTGdp+BdBsjvPPjl8WMjnrjObTuhVSYOjWFVb5BbmmNAUiW/Bl9hvxVrAkjE3WWcRhiBeskzQCqtpcE=
  - secure: W3G8326zMyMjK2RHs5IHqKOPy5879Z/9C6xdAlhps5w8YIMILfDKxOmOzYuYV3rFVRl4dWrKWM9GkvjB4lR+6D5n5bZGa4rNC2vkVLTL4Jz3TbDaKuw4E4QnoCSNo+iprAkI20wHWPNvp2woM+HF/e0DE06DY3zS0pzI5QcpgL74XSFbsaf4GnoXqY/eHSWD442CegrGOTCIAWuPF2b14GSv9IwYzSrvW+A79m5rAFKLUQgx4hGLql3ujdxLuyYXN7kzOGy5lePi7LssoOvHSe4UJ9CPl/8Yz+B5sPzbvjUmewgrXjd64U7l2eyQPuTRA04gXMULk3c02ROtb8FrDn9x3NC/mXB9V+EO2JpuC+MvViEi/HB1kHsaRXdJVlFOvBi65u5ac2xu+8l82Cv4Hh4GYQKrqsFmiSzJ+SaSuyo9un+bVxUjv06h4sy+LhFoq+L2q5Ev3eC/H93LCGXbXEW3F5UV6KI1KX8uptUSIG5gOoK7TnPDEipBUtQaY6+QaSqU3sXet9NgkGZzurg2twhSOqUR3nedjJk8LffB2p4zz1esqTPFTUkQ1cHMM+0yl4ujlGS9Xb6SjQnLxBFqwTYJIjcr2D3S+nOiWRcJr1a7hGvYSqIw5gYfKMEpybHUp9q5lsDF25VO7R+wIsBUjZHPtgjUKE+cPP3XctIV0AE=
deploy:
  provider: pypi
  edge: true
  username: __token__
  skip-existing: true
  distributions: "sdist"
  on:
    branch: master
  password:
    secure: lcMLonhz6DYwh1HQ2nRn3X4DJplMEMDzTmzcrKocZE39PctapPKz1VfYEcbV91OAa473+r6NfWmikYU0hvEgWQfXx3/SgF5JZwFsonB5E2vC/+JghXuN5mEwlyvQ5v6+9adafIQ5qGT/hKgE4eomBYH9AJZBuMnnzsD64QkC0Lh8SFoaxGZH5MljEtLKz9crLAraa1s4XChM9yQeF/7y5XG5S7BR/iV07Te4axpNM5L2SvuHFtX0TEH2xn+hCzMFrOVNgWD4cgnby4KDB0XG5R+kOqsMXpLqqCb9QDnzjPzVrWtdWWPrCWCPG7ix2gVdqjKw92OAqIs0Gj1Hreu3zyEg8Pvtln0NUpPX1YWE6I+HcFUgl0zgMV1mjCmp5DdOLHXzOUIlzej/qjeb3DSX0fvYkFVWT3NEkFngM+Ay9e9Tf2teiENGOE5IlW0UyccPqbkoMIgT7zIEvOEnJTilb42G6Mt5vp64EuH/dUBx/HweWK+kzPomUN0+/XD4KOmOAH5MGy7IjOROBj+SNiNOyOT/gdiaLtdUIFBBbjbgABRCA9y1yc87sQpfuQgvukPJFI1Sn8r00dm7xJEkfeh3uOFC8ssHKUfRqeRKQiQaQrVszOeUnUpOJqcXRDf7+qYpPHzYjZZVmrjf6lze1uX2veu5eNS1TppMeszYn9e1vSg=
